# Generated by Django 4.2.6 on 2023-11-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('handle', models.SlugField(default='')),
                ('age', models.CharField(max_length=2)),
                ('parent_first_contact', models.CharField(max_length=11)),
                ('parent_second_contact', models.CharField(blank=True, max_length=11, null=True)),
                ('kid_class', models.CharField(choices=[('Daycare', 'Daycare'), ('Nursery', 'Nursery')], default='Nursery', max_length=7)),
                ('kid_picture', models.ImageField(blank=True, null=True, upload_to='kids_image_gallery')),
            ],
            options={
                'ordering': ('-full_name',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=7)),
                ('handle', models.SlugField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for', models.CharField(choices=[('Book', 'Books'), ('School Fees', 'School Fees'), ('Monthly Fee', 'Monthly Fee')], default='School Fees', max_length=11)),
                ('payment_type', models.CharField(choices=[('Part Payment', 'Part Payment'), ('Complete Payment', 'Complete Payment')], default='Complete Payment', max_length=16)),
                ('amount', models.CharField(max_length=11)),
                ('handle', models.SlugField(default='')),
                ('paid_on', models.DateField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kid')),
                ('term_paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term')),
            ],
            options={
                'ordering': ('-paid_on',),
            },
        ),
        migrations.AddField(
            model_name='kid',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term'),
        ),
    ]
